version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raasystem-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app    # local live reload
    command: ["node", "server.js"]

